### ISSUE TITLE
Restore systray icon after Explorer restart?

### ISSUE THREAD

**Issue by TarkusLV** [nayuki/NetPerSec#3]
I know this is a long shot, since there has been no development in years.  That said, the one thing I don't like about this app is the systray icon doesn't get restored after Explorer crashes or is restarted purposely.  I have to kill NetPerSec and then restart it to get the icon back.  It's the only systray program I use that doesn't restore its icon.

Not a major deal, but perhaps if there becomes any new development, this can be addressed.

Thanks.

**Comment by nayuki** [comment]
I understand what you mean and have experienced the same issue. Also NetPerSec is not the only problem with this bug. But I'm sorry I can't fix it because I don't know Windows APIs.

**Comment by nayuki** [comment]
I understand what you mean and have experienced the same issue. Also NetPerSec is not the only problem with this bug. But I'm sorry I can't fix it because I don't know Windows APIs.

To put my situation in context, this is what I wrote on this project's web page https://www.nayuki.io/page/netpersec-nayukis-version :

> This page features an updated version of the program by Nayuki in 2016 – the functionality is slightly improved and the source code is heavily cleaned up. Despite the work I contributed to this project, this is considered to be only a maintenance update to the NetPerSec application. Windows C++ programming still confounds me enough that there is little hope of adding or modifying any non-trivial part of the software.
